### ISSUE TITLE
Menu item allows `null` route name but not when rendered

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#110]
When building the User menu item, we allow to add `null` route name.

https://github.com/kevinpapst/TablerBundle/blob/908548e4d6ac0ed94eb3e0ab75364c8a76111e1b/src/Model/MenuItemModel.php#L59-L65

But when MenuItem is used to render the actual item, 
PHP throw an error that `null` cannot be of type `sting`.

`KevinPapst\TablerBundle\Twig\RuntimeExtension::getRouteByAlias(): Argument #1 ($routeName) must be of type string, null given`

https://github.com/kevinpapst/TablerBundle/blob/908548e4d6ac0ed94eb3e0ab75364c8a76111e1b/src/Twig/RuntimeExtension.php#L48-L52

------

#### Possible fix
When route is `null` set `#` as href link.

**Comment by kevinpapst** [comment]
Null must be allowed for dropdown/multi-level menus. Having a leaf item without a route sounds kinda wrong to me, but I agree that we should handle that properly :D showing a empty anchor `#` url segment is a good approach.
