### ISSUE TITLE
Update Tabler to beta15

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#125]
To continue #124
They have fixed https://github.com/tabler/tabler/issues/1335 in https://github.com/tabler/tabler/releases/tag/v1.0.0-beta15

To be able to finish that part, we need to upgrade Tabler to beta 15 🚀 

Is it OK for you @kevinpapst?

**Comment by kevinpapst** [comment]
Sure, did it just now. Both the bundle and the demo were updated to beta 15.

**Comment by cavasinf** [comment]
Nice 👍
