### ISSUE TITLE
[Symfony FLEX] tabler.yaml not copied

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#15]
When installing the bundle from composer with Symfony FLEX,
the file `config/packages/tabler.yaml` is not copied from the bundle.

bundles.php works fine, but not tabler.yaml.

Need to register a Flex recipe

**Comment by tacman** [comment]
With flex 1.17+, you can also register your own endpoint for recipes.  I started playing around with that and find it easier than going through the official contrib recipes repo.

https://symfony.com/blog/symfony-flex-is-going-serverless

**Comment by kevinpapst** [comment]
All the work so the dev does not have to copy the one config file ??? 

If someone ones to take over long term maintainer role for the recipe: please. I did it once for AdminLTE and it is not worth the trouble IMO.

Anyways, I adjusted the README and removed the Flex part (which was copy&paste from the official symfony docs) => so this is not a "bug" anymore

**Comment by cavasinf** [comment]
Configuration doc already refer that part https://github.com/kevinpapst/TablerBundle#step-2-configure-the-bundle.

Closing this issue.
