### ISSUE TITLE
[Buttons] Error with `templates/components`

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#16]
## Expected behavior
I'm trying to figure out how to use the button components created for Tabler.
What I want is a button of class `btn-link` without any icon.

Here's what I'm trying to achieve:
![image](https://user-images.githubusercontent.com/25293190/145559523-25c49e67-a6b6-4a40-9acc-da94730090e8.png)

## Cases

Two cases messing me out:

### N° 1 
By using [`components/button.html.twig`](https://github.com/kevinpapst/TablerBundle/blob/014debb4a80785a99d070259b62cc34d4be2ad90/templates/components/button.html.twig#L1), 
I cannot find a way to use the macro `button()` without an icon.

My code:
```twig
{% from '@Tabler/components/button.html.twig' import button %}
{{ button(false, { title : 'action.back_to_list'|trans, combined : true, url : path('admin_post_index') }, 'link') }}
```

Result:
![image](https://user-images.githubusercontent.com/25293190/145559916-12783b6c-99de-4e68-a1eb-97299df9a9f8.png)

### N° 2
By using [`components/buttons.html.twig`](https://github.com/kevinpapst/TablerBundle/blob/014debb4a80785a99d070259b62cc34d4be2ad90/templates/components/buttons.html.twig#L19), 
I've got an error with the macro `link_button()` about the `ContextHelper`. (even with no default values)

My code:
```twig
{% from '@Tabler/components/buttons.html.twig' import link_button %}
{{ link_button('test', '#', 'eye', "link", "lg") }}
```

`default(tabler_bundle.button.size)` trigger that error:

![image](https://user-images.githubusercontent.com/25293190/145559205-5b0cd0f1-7c14-4971-9826-14146d0faa5c.png)

**Comment by kevinpapst** [comment]
Ok, quick look shows the the `{# TODO test me #}` above the macro.
I am not using this macro anywhere and have no use-case for it.
And the Demo app is not yet build, so I haven't even tried it... again: sorry 🤷 

Can you fix the macro? I find it easiest if you have a real world use-case for it.

**Comment by cavasinf** [comment]
There is no `button` in ContextHelper used by `tabler_bundle.button`.

How do you want to handle all default aspect (button and others) in the Bundle ?
- Raw values
- Do we let the dev to change default config via the `tabler.yml`
```yaml
tabler:
    options:
        dark_mode: false
        [...]

    default:
        button:
            size: md
            type: primary

        [...]
```

**Comment by kevinpapst** [comment]
I don't think we need configurable default values. We can document that users should wrap the functions.
I do it like this, so I can always change the values independently from the bundle:

```
{% macro action_button(icon, values, type) %}
    {% import '@theme/components/button.html.twig' as macro %}
    {{ macro.button(icon, values, type) }}
{% endmacro %}
```

The other error is fixed and I added examples how to use the embed to the demo app.
