### ISSUE TITLE
Support Symfony 7 in TablerBundle

### ISSUE THREAD

**Issue by tacman** [kevinpapst/TablerBundle#171]
Since Symfony 7 will be out in 2 months, it would be great if this bundle supported it.

I've updated my branch of the Tabler Demo and it appears to be working well with Symfony 6.4.  I can test with Symfony 7 as well.

Also, if we made the minimum requirement as 6.1, we could benefit from the easier bundle configuration, by extending from AbstractBundle.

**Comment by kevinpapst** [comment]
Yes please, if you help testing that would be great!

**Comment by kevinpapst** [comment]
I am using SF 6.4 and have no deprecations, so I added 7.0 compatibility to composer.

Relased with https://github.com/kevinpapst/TablerBundle/releases/tag/1.3.0
