### ISSUE TITLE
Flash messages not displayed after redirectToRoute()

### ISSUE THREAD

**Issue by LiaraAlis** [kevinpapst/TablerBundle#175]
When using `$this->addFlash(...)` before using `$this->redirectToRoute(...)` flash messages are not displayed.
It works when adjusting conditions in `flash_messages.html.twig`:
```diff
- {% if app.session and app.session.started and app.session.flashbag.peekAll|length > 0 %}
+ {% app.session.flashbag.peekAll|length > 0 %}
    <div class="row">
        <div class="col-sm-12">
            {{ macro.session_flash(true, false, '', 'flashmessages') }}
        </div>
    </div>
{% endif %}
```

It also works when calling `$this->container->get('request_stack')->getSession()->start();` in the target route.
I'm not sure whats the better way. In official symfony discussion, there is no check if the session is started. But I think it is needed here in case that session component is not enabled. But in my opinion it is also not best practice to start session explicit.

What do you think?

**Comment by kevinpapst** [comment]
The entire Kimai core is using flashSuccess() or flashError() and then redirecting afterwards.
I am using this code since years in different apps.
Don't you use session auto start ?

**Comment by LiaraAlis** [comment]
@kevinpapst There is no auto start in Symfony 6. Sessions are only started when reading or writing to session. See docs: https://symfony.com/doc/current/session.html

**Comment by kevinpapst** [comment]
I do not understand why your change should make a difference.
When you add a flash message, it will be stored in the session (if non existing, one should be started).
Did you check the difference in the compiled template between your code and mine?

**Comment by LiaraAlis** [comment]
It is because in your code it first checks if the session has been started. Only then it reads from the session.
But if the session is not started manually (that's how I solve this temporarily, so that I don't have to change the template) and also otherwise neither read from nor written to the session, it is still not started. By my change this check is omitted and the session is started.

The problem with this is should be, that the session is always started, which is a problem. Therefore the whole thing should be wrapped with a check for `app.request.hasPreviousSession` which is described in an older version of the docs: https://symfony.com/doc/4.1/session/avoid_session_start.html
So I suggest to check if my suggested change above starts the session and if this check could work to avoid this behavior.

Maybe you should also change the reading of the flash messages to `app.flashes` as it is described in the doc. But this is another topic.

**Comment by kevinpapst** [comment]
Okay, I never used flash messages in an anonymous context, that's why I never saw that problem.

Can you send a PR to address both issues: the hasPreviousSession check and using app.flashes ?

**Comment by LiaraAlis** [comment]
I'll test this again more closely and then do a PR if needed.

**Comment by kevinpapst** [comment]
Is this still an issue @LiaraAlis ?

**Comment by LiaraAlis** [comment]
Strangely enough, I can no longer reproduce the problem. It now also seems to work if the session is not explicitly started beforehand. However, I don't know whether this is perhaps due to other changes in my project. I have not yet been able to test it in a new project.
