### ISSUE TITLE
[Docs] Dynamic theme options (like dark mode)

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#178]
The dark theme is defined from `tabler.yaml` for each user.
This should be a default value if the user hasn't set his preferences.
If the user wants to switch to dark theme (and `tabler.yaml` is set to light), 
there's no way to override this behavior.

We should allow to set the dark mode with a subscriber/listener, 
and the current value of `tabler_theme()` should be the default value if there is no subscriber/data provided.

Example in a simple twig `data-bs-theme="{{ app.request.cookies.get('tablerTheme', tabler_theme()) }}"`, 
dark theme comes from a cookie, and if undefined it will get the value of `tabler_theme()` (which is `tabler.yaml`).

Cookie is not the only case, some projects get user preferences from the database (hence the need for subscriber).

WDYT?

**Comment by kevinpapst** [comment]
That's what the ContextHelper is for.

I use this code. Go grab and adapt:
https://github.com/kimai/kimai/blob/main/src/EventSubscriber/ThemeOptionsSubscriber.php#L62

I do not need more than that. This is Symfony, so I'd say that we can safely assume these settings come from the backend?!

**Comment by cavasinf** [comment]
> That's what the ContextHelper is for.

True!!

--------------

To complete the example above with cookies:
```php
use KevinPapst\TablerBundle\Helper\ContextHelper;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\KernelEvent;
use Symfony\Component\HttpKernel\KernelEvents;

final class TablerThemeOptionsSubscriber implements EventSubscriberInterface
{
    public function __construct(
        private readonly ContextHelper $contextHelper,
    ) {
    }

    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::CONTROLLER => ['setThemeOptions', 100],
        ];
    }

    public function setThemeOptions(KernelEvent $event): void
    {
        if (!$event->isMainRequest()) {
            return;
        }

        if ($event->getRequest()->cookies->has('tablerTheme')) {
            $tablerTheme = $event->getRequest()->cookies->get('tablerTheme');
            $darkMode    = $tablerTheme === "dark";
            $this->contextHelper->setIsDarkMode($darkMode);
            if ($darkMode) {
                $this->contextHelper->setIsHeaderDark(true);
                $this->contextHelper->setIsNavbarDark(true);
            }
        }
    }
}
```

**Comment by kevinpapst** [comment]
Actually a good idea to include that in the docs, reopen
