### ISSUE TITLE
Title block names - Wrongly named

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#19]
When using the blocks for header titles, there names can be not comprehended by devs (and me).

We are talking about `subtitle` and `title`.
Or in Tabler, it's more `pretitle` and `title`.

### Example 
My page is a `List of products` that come from `Products`.
Breadcrumb would be : `Products > List of products`.

|  | Tabler.io | TablerBundle |
|:---:|:---:|:---:|
| Variable | ![image](https://user-images.githubusercontent.com/25293190/145596355-f35551ea-1e04-459f-87fa-3928bebd9b7b.png) | ![image](https://user-images.githubusercontent.com/25293190/145595699-7aa35aa8-f060-4f89-bc9e-9f5fc94169ff.png) |  
| Example | ![image](https://user-images.githubusercontent.com/25293190/145596646-d60b075f-f734-441a-a9e3-0f449cd57a69.png) | ![image](https://user-images.githubusercontent.com/25293190/145596764-3b037e63-f2f3-40fc-8ef5-1d3abc44fbb2.png) |

I think it's more normal/user friendly to have the main title more bigger and wider than the pretitle.

⚠️ Renaming a block can break existing projects ⚠️

**Comment by cavasinf** [comment]
@kevinpapst any thought on that ?

**Comment by kevinpapst** [comment]
There is no BC policy that we yet have to stick to. This bundle is WIP.
I just don't understand the issue. You want to switch block names?

**Comment by cavasinf** [comment]
Yes, I think it's better to stick with Tabler variable name:
Switch `page_subtitle` into `page_pretitle`.

## Explication

I guess, the current names are a rest from AdminLTE. 
Which works for AdminLTE template:
![image](https://user-images.githubusercontent.com/25293190/145805450-1b0f93ca-b0e8-4f1e-8f84-c0be6b9fe04e.png)

But if we stick with those today variable names, 
it look like kinda reversed between title and subtitle.
![image](https://user-images.githubusercontent.com/25293190/145805674-0e278696-c4c0-424c-85f8-29214d0070e9.png)

**Comment by kevinpapst** [comment]
Yes, the names make the transition easier and I don't think it really matters.
That is a bit like the discussion about CSS class names: name it after "what it does" or "where it is used"?

Using `pre` explains where it is placed and `sub` describes that this is an additional info about the current page.

Personally I'd always say I am on the page "General UI" here. Do you want to make "Prevew of UI Elements" big in this example?

**Comment by cavasinf** [comment]
> Do you want to make "Prevew of UI Elements" big in this example?

Yup, that what I try to explain..

With AdminLTE, you read it from left to right, so you know "from what/where you are". 
Previous page => Current page✔️ 
With Tabler, you read from top to down, in that case it is reversed. 
Current page => Previous page❌ 

-----------

>Using `pre` explains where it is placed and `sub` describes that this is an additional info about the current page.

Is it not weird to have "additional info about the current page" BEFORE the "info of the current page" ?

**Comment by kevinpapst** [comment]
What about we use `{% block page_pretitle %}{% block page_subtitle %}Overview{% endblock %}{% endblock %}` ? 
Makes it easier when migrating AdminLTE apps and we only document (once documentation is there) the new block.

**Comment by cavasinf** [comment]
Yes that can do the "trick", hybrid way.

Do you mind to leave it like that all the life-span, or just for migrating time.

**Comment by kevinpapst** [comment]
Lets remove it with the second major release and mention it in the "migration" docs.

**Comment by cavasinf** [comment]
Waiting resolution/brainstorming of #21

**Comment by cavasinf** [comment]
Merged in https://github.com/kevinpapst/TablerBundle/pull/48

**Comment by kevinpapst** [comment]
Would be cool if we could track all available blocks and such in the demo app.
