### ISSUE TITLE
Breadcrumb that is not a real breadcrumb

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#21]
## Context 📋 
In the `page-header`,
I want to add buttons like `Create new`, 
![image](https://user-images.githubusercontent.com/25293190/145976473-695e6134-692c-40e6-b28a-f319b096a6a2.png)

and still have the breadcrumb: `Items > Actions`.
![image](https://user-images.githubusercontent.com/25293190/145976527-76df4e0a-762d-4d4f-9511-48e1c45f97ec.png)

## Current state 👀 
Page header buttons are at the position of `Breadcrumb`.
https://github.com/kevinpapst/TablerBundle/blob/014debb4a80785a99d070259b62cc34d4be2ad90/templates/layout.html.twig#L96-L109

## Problem ❌ 

With that current state,
- If I want to add my buttons, I'll put them INSIDE breadcrumb block with custom HTML to allow to have Buttons + Breadcrumb.
- Plus, we are declaring a block about Breadcrumb with buttons on default values. In that case, it's not really a "Breadcrumb".

## Possible solution ✔️ 

Split current `{% block breadcrumb %}` into 3 blocks
```twig
{% block page_header_right %}
    <div class="col-auto ms-auto d-print-none">
        {% block page_header_actions %}
            <div class="btn-list">
                <a href="#" class="btn btn-white">
                    New view
                </a>
                <a href="#" class="btn btn-primary d-none d-sm-inline-block">
                    Create new report
                </a>
            </div>
        {% endblock %}
        {% block breadcrumb_container %}
            <div class="text-end">
                {% block breadcrumb %}
                    Entity > Action > ...
                {% endblock %}
            </div>
        {% endblock %}
    </div>
{% endblock %}
```

**Comment by cavasinf** [comment]
Other solution could be to use `page_stats` as breadcrumb.
And rename `breadcrumb` into `page_header_actions`

![image](https://user-images.githubusercontent.com/25293190/145990640-29a7480d-f150-44a6-af8b-a4407f76f23b.png)

**Comment by kevinpapst** [comment]
Hm, I would always try to keep the menu level as flat as possible. 
And then you could switch page title and pre title and add a link to the pre title - in your example: `Articles` would be the `pre_title` with a link and `Create article` would be the title.

The other solution I would prefer are be the 3 blocks. 
But I would keep the breadcrumb on the left side (start for RTL) and followed by the buttons on right side (end for RTL).

**Comment by cavasinf** [comment]
> Hm, I would always try to keep the menu level as flat as possible.

Ok
> And then you could switch page title and pre title and add a link to the pre title - in your example: `Articles` would be the `pre_title` with a link and `Create article` would be the title.

Ok that is about #19

> The other solution I would prefer are be the 3 blocks.

Ok

> keep the breadcrumb on the left side

> followed by the buttons on right side

Left side of the header buttons ?

**Comment by cavasinf** [comment]
@kevinpapst up 😉

**Comment by kevinpapst** [comment]
What is missing? You mean that:

>Left side of the header buttons ? Like that ?

Then I would say yes, just make it "start" and not "left". Quote from bootstrap docs:

> For example, instead of .ml-3 for margin-left, use .ms-3.

**Comment by cavasinf** [comment]
Yeah,I was waiting an answer about the **breadcrumb** position VS _buttons_ position.

I was OK with the 3 blocks, but I don' know on which order you want the breadcrumb.

| Position | Demo |
|:----:|:----:|
| `Top` | ![image](https://user-images.githubusercontent.com/25293190/146364781-f7137751-b206-4283-9912-e3c56d9e2af9.png) |
| `Bottom` | ![image](https://user-images.githubusercontent.com/25293190/146364698-ef3ad114-f2a5-4811-a817-9dd0697a86bb.png) |
| `Left` | ![image](https://user-images.githubusercontent.com/25293190/146365100-542b9740-18e9-400d-83b8-15ac0aff04fc.png) |
| `Right` | ![image](https://user-images.githubusercontent.com/25293190/146365230-bb221769-c09e-4bdd-8a62-4b10bfc3d74f.png) |

In `Left` mode, Breadcrumb will move depending on the action buttons.
I don't know if it is good for the end user (not dev) to move the breadcrumb on different cases.
Breadcrumb is a landmark/reference, If we change his position it could be messing up with user.

In `Right` mode, buttons will move depending of the Breadcrumb.

**Comment by cavasinf** [comment]
@kevinpapst IMO `Top` mode is the better choice

**Comment by kevinpapst** [comment]
Hmmmm, I don' really like any of these. Too many clickable elements next to each other. 
Why not replacing "subtitle" with the breadcrumb? The information is partially duplicated there anyways.

I find the top position the least intrusive one (with a little bit of added bottom margin).

**Comment by cavasinf** [comment]
> I don' really like any of these

What about the `page_stats` then ? https://github.com/kevinpapst/TablerBundle/issues/21#issuecomment-993451128

**Comment by kevinpapst** [comment]
I would prefer if the original Tabler bundle had a showcase for the breadcrumb... so I [posted the question upstream](https://github.com/tabler/tabler/issues/975).

Honestly: for now I would prefer if you would add the breadcrumb in your custom layout. Then you can use any block that you want. Overwrite page_stats or any other block, add the breadcrumb and call {{ parent() }}.

And then, after collecting some user feedback => share it in the upstream discussion. Maybe we can get an example in the official demo.

**Comment by cavasinf** [comment]
Waiting for an answer from Tabler then. 👍 

> add the breadcrumb in your custom layout

I'm OK with that. But `breadcrumb` is already taken, and it will contain buttons..
https://github.com/kevinpapst/TablerBundle/blob/058fd31189cfcc1dc249a5fd0f359aed13f1ccbd/templates/layout.html.twig#L97-L106

I can manage to create an `page_header_actions` block INSIDE the current `breadcrumb` block.
And create a new block `breadcrumb_custom` INSIDE `page_stats`.

Bit tricky, but should do the job.

**Comment by kevinpapst** [comment]
Then let's rename the breadcrumb block to page_actions? And add it to the migration guide.

**Comment by kevinpapst** [comment]
Have you seen the answers?

**Comment by cavasinf** [comment]
Yes, 
It will update #19 again 😄 

How can we place `subtitle` block and `breadcrumb` block in the template.
According to their answer, there are at the same place.

Not that simple with block template pre-created 🤔

**Comment by kevinpapst** [comment]
Why? Can't you simply put `{% block breadcrumb %}` into `{% block pretitle %}`?

**Comment by cavasinf** [comment]
ATM we have to place.

- page_pretitle
- page_subtitle (from AdminLTE)
- page_title
- page_stats
- breadcrumb (also used in AdminLTE)

It can be like:
```twig
{% block page_pretitle%}{% block breadcrumb %}{% endblock %}{% endblock %}
{% block page_title%}{% endblock %}
{% block page_stats %}{% block page_subtitle %}{% endblock %}{% endblock %}
```

**Comment by cavasinf** [comment]
Merged in https://github.com/kevinpapst/TablerBundle/pull/48
