### ISSUE TITLE
Certain FontAwesome icons are too wide

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#26]
## Context
With FontAwesome in certain icon case:
- fa-users
- fa-cogs
- ...

When using twig macro `tabler_icon()`, 
icons are to wide and overflow the parent element.
![image](https://user-images.githubusercontent.com/25293190/146331445-2874013d-b215-4721-b469-c913da680438.png)

## Problem
At the end, 
the margin right on the `icon` class is not enough and label is too close from the icon.

<table>
    <tbody>
        <tr>
            <td rowspan=4><img src="https://user-images.githubusercontent.com/25293190/146331600-b223f479-4413-434f-a9f7-e52253b022f7.png"/></td>
            <td>Home ❌</td>
        </tr>
        <tr>
            <td>Tiers ❌ </td>
        </tr>
        <tr>
            <td>Liste des Tiers ✔️ </td>
        </tr>
        <tr>
            <td>Créer un Tiers ✔️</td>
        </tr>
    </tbody>
</table>

## Possible better case
If I remove the `icon` class from the `<i>`
![image](https://user-images.githubusercontent.com/25293190/146332233-a02084d7-5085-4f64-9b3f-436541683d33.png)

**Comment by kevinpapst** [comment]
Yeah, there is the `$isIcon` Parameter in the function call. Can you try to replace `{{ tabler_icon(item.icon) }}` with `{{ tabler_icon(item.icon, null, false) }}` and check the vertical menu as well.
I know that there are places where it causes issues when the "icon" class is missing. 

I assume this is actual a CSS issue coming from the fact that Tabler uses the SVG icons by default.
I really need to figure out a way to switch between these icon packs... but that is another issue

**Comment by kevinpapst** [comment]
Fixed in #18
