### ISSUE TITLE
[Templating] Create macro for submit_button

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#27]
### Discussed in https://github.com/kevinpapst/TablerBundle/discussions/23

<div type='discussions-op-text'>

<sup>Originally posted by **cavasinf** December 14, 2021</sup>
@kevinpapst just curious, how do you render your submit form button.

From the embeds/button macro you can only create a fake button through `<a>` element. In that case, no submit type possible.

So, did you create it from your formbuilder and render it via form_row() ?</div>

**Comment by kevinpapst** [comment]
Until now I rendered the buttons manually. Some examples:

In a modal footer:
```
<button type="submit" class="btn btn-primary pull-left modal-form-save" data-loading-text="{{ (submit_button|default('action.save'))|trans }}…" id="{{ block('modal_id') }}_save">{{ (submit_button|default('action.save'))|trans }}</button>
```

In a delete dialog: 
```
<button type="submit" class="btn {% if used %}btn-danger{% else %}btn-primary{% endif %} pull-left modal-form-save" data-loading-text="{{ 'action.delete'|trans }}..." id="{{ block('modal_id') }}_save">{{ 'action.delete'|trans }}</button>
```

In a regular form:
```
<input type="submit" data-loading-text="{{ (submit_button|default('action.save'))|trans }}…" value="{{ (submit_button|default('action.save'))|trans }}" class="btn btn-primary" />
```

**Comment by cavasinf** [comment]
Merged in https://github.com/kevinpapst/TablerBundle/pull/47
