### ISSUE TITLE
[Templating] "Missing" Twig Block page_header

### ISSUE THREAD

**Issue by creiner** [kevinpapst/TablerBundle#30]
Hi,
I'm currently experimenting with the bundle in a prototype. Thanks for the effort!
I would propose to add a new block (maybe named: page_header) to the default layout.
The content of the block would be the following div;
https://github.com/kevinpapst/TablerBundle/blob/14ac8dcbb1324b899be4f75c613b8bba896452f7/templates/layout.html.twig#L79-L110
With this block it would be possible to hide all the header elements (page_subtitle, page_title, page_stats and breadcrumb) for a clean layout.
Thanks
Chris

**Comment by cavasinf** [comment]
Implemented by https://github.com/kevinpapst/TablerBundle/pull/31
