### ISSUE TITLE
TablerBundle card `collapsible` VS Tabler `Accordion`

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#41]
Collapsible cards doesn't have the "current state" effect on the button to know if it's collapsed or not.

![CardCollapsible](https://user-images.githubusercontent.com/25293190/146776705-33f693f1-b9d1-4131-a2b8-e77427f11226.gif)

I was trying to find how Tabler handle collapsible cards, and I don't find any.
But instead I've found those [Accordions](https://preview.tabler.io/accordion.html).

It made me thinking that it was a custom card made by @kevinpapst. Am I right ?

Is that conceivable to use Accordions effect for collapsible card instead ?

**Comment by kevinpapst** [comment]
It is a feature carried over from AdminLTE and adapted to work with Tabler. 

Accordions are using card internally, but to me they are two different features.

The issue appears if you use other card action buttons (I will update the demo app to include examples):
<img width="828" alt="Bildschirmfoto 2021-12-20 um 15 00 58" src="https://user-images.githubusercontent.com/533162/146778890-9f1c7511-be75-4568-b274-a776f79a5809.png">

So if we change it, it must go hand in hand with additional buttons and change their appearance as well.

I updated the demo app to showcase the issue in combination with the available `action_cardtoolbutton` macro:
<img width="648" alt="Bildschirmfoto 2021-12-20 um 15 12 32" src="https://user-images.githubusercontent.com/533162/146780371-81666d7b-1d0d-4b38-af8f-38cca07568e0.png">

If you use action buttons in card headers, they should all look the same. The accordion button style is different.
And regular end user already have an issue finding action buttons, let alone if we would remove the border.

Probably we should add an embed and helper macros for the accordion and then come back here?

**Comment by cavasinf** [comment]
IMO from a dev perspective (not Bundle dev), 
action buttons in "card headers" and "collapsible" cannot be together.

With your example, it's weird to be able to a edit card that is not "open" or readable.
Even if the edit button trigger the collapse event.

<hr>

Anyway,
with what Tabler has done on the accordion, we cannot add multiple button on the header.
Because the title is one GIANT button. 

![image](https://user-images.githubusercontent.com/25293190/146790740-16251b4a-e140-40bf-8da4-536ca4e785ac.png)
![image](https://user-images.githubusercontent.com/25293190/146790778-e87d832b-7715-4cc3-9454-7bc54013d52b.png)


What is cool with that is the click event which open the "card" is binded anywhere on the "header".

![accordion](https://user-images.githubusercontent.com/25293190/146791449-148499ea-a0e6-4335-b99b-00bfe6b8751d.gif)

At the end, I don't know what is the better 😄 
Collapsible card is useful, but out of bound from Tabler.
Accordion is cool, but need a full implementation like card embed today..

I don't know if I have the time, but I can take a look how to make a macro about that

**Comment by cavasinf** [comment]
I've achieved to make a false "card" from an accordion. (live code with Firefox from Tabler.io)

![accordionCard](https://user-images.githubusercontent.com/25293190/146796485-5e52c8b7-64fc-4240-b1a1-4f69c064159f.gif)


```html
<div class="page-body">
  <div class="container-xl">
    <div id="accordion-example" class="card accordion">
      <div class="">
        <h2 class="accordion-header" id="heading-1">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-1" aria-expanded="true">
            <i class="fas fa-search me-1"></i>Filtre </button>
        </h2>
        <div id="collapse-1" data-bs-parent="#accordion-example" style="" class="accordion-collapse border-top collapse show">
          <div class="accordion-body">
            <div class="row">
              <div class="col-auto">
                <div class="mb-3">
                  <label class="form-label" for="tiers_filter_type">Type</label>
                  <select id="tiers_filter_type" name="tiers_filter[type]" class="form-select">
                    <option value="">Tous</option>
                    <option value="client">Client</option>
                    <option value="entreprise">Entreprise</option>
                  </select>
                </div>
              </div>
              <div class="col">
                <div class="mb-3">
                  <label for="tiers_filter_socialReason" class="form-label">Raison sociale</label>
                  <input type="text" id="tiers_filter_socialReason" name="tiers_filter[socialReason]" placeholder="Raison sociale" class="form-control">
                </div>
              </div>
            </div>
          </div>
          <div class="card-footer">
            <div class="d-flex">
              <button type="submit" id="tiers_filter_reset" name="tiers_filter[reset]" class="btn btn-warning reset-cookie-form-action btn">
                <i class="fas fa-eraser me-1"></i>Effacer filtre </button>
              <button type="submit" id="tiers_filter_filter_data" name="tiers_filter[filter_data]" class="btn btn-primary ms-auto btn">
                <i class="fas fa-search me-1"></i>Filtrer </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by cavasinf** [comment]
@kevinpapst new version of Cards from Tabler.io is here : https://preview.tabler.io/card-actions.html

There's now an `.card-actions` class to allow buttons and other.

ATE, we should implement `accordions` and new `cards`

**Comment by kevinpapst** [comment]
The class `card-actions` is already in use in the card embed.
I updated to the latest beta release and there were no changes showing.
Maybe you can double check.
Yes to the accordion! I'd like to have that as well, then we can remove the collapsible button from the card.
