### ISSUE TITLE
Allow dev to choose navbar color light/dark (class)

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#43]
With the current state,
Navbar color is hard coded (`navbar-light`):

https://github.com/kevinpapst/TablerBundle/blob/e5a0366914b4682d734c89b0e62600612b7b1bbe/templates/layout.html.twig#L25
https://github.com/kevinpapst/TablerBundle/blob/e5a0366914b4682d734c89b0e62600612b7b1bbe/templates/layout.html.twig#L65

We need to allow dev to choose between navbar dark or light.

⚠️ Changes must be done with layer vertical and horizontal ⚠️ 
SEE https://github.com/kevinpapst/TablerBundle/pull/3

**Comment by kevinpapst** [comment]
And in line https://github.com/kevinpapst/TablerBundle/blob/e5a0366914b4682d734c89b0e62600612b7b1bbe/templates/layout.html.twig#L65

When I set 'body class="theme-dark"` then the navbar is dark, even if it has the class `navbar-light`.

**Comment by cavasinf** [comment]
`theme-dark` override every `-light` class configuration.

For me it is a normal behavior, do you see something wrong with that ?

What I want to do is:
Horizontal :
- Dark: https://preview.tabler.io/layout-navbar-dark.html?theme=light
- Light: https://preview.tabler.io/layout-horizontal.html?theme=light

Vertical:
- Dark: https://preview.tabler.io/layout-vertical.html?theme=light
- Light: https://preview.tabler.io/layout-vertical-transparent.html?theme=light

Vertical condensed:
- Light: https://preview.tabler.io/layout-combo.html?theme=light
- Dark: No demo from Tabler
![image](https://user-images.githubusercontent.com/25293190/146941078-a9a1dd48-fde7-403a-a63b-1b17ab4f13b8.png)
