### ISSUE TITLE
[MenuBuilder] Hard codded parent item href ?

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#45]
https://github.com/kevinpapst/TablerBundle/blob/2e96587a8a7709e3892bc52b46a5354a6935630a/templates/includes/menu.html.twig#L9

This `href="#navbar-base"`, is hard codded.

Tabler.io has the same functionality but with different names.
TBH, I don't understand what is the point of that.

**Comment by kevinpapst** [comment]
Hm, just had a quick look. The ID is not used for anything and I guess it is better if it does not exist on the page.
As it works for me I don't really care and would prefer not wasting any more time thinking about it 😁 

But if you have an issue with it: can you please elaborate what you see as problem here?

**Comment by cavasinf** [comment]
When using SWUP JS, 
it triggers me a warning every time I open a menu item:
![image](https://user-images.githubusercontent.com/25293190/148762714-b9a2b336-7e83-4ce6-bdac-35d3e0c34fd4.png)

**Comment by kevinpapst** [comment]
I don't know SWUP JS, but if you find a way to fix the issue, please go ahead and sent a PR. 
Isn't there some way to tell swup to ignore certain html elements?

**Comment by cavasinf** [comment]
SWUP JS is looking for any HTML URI fragment (#).

I think it's better that the template allow us to put anything, instead of trying to override SWUP default behavior.

I've asked https://github.com/tabler/tabler/discussions/993 what is the purpose of that.

**Comment by kevinpapst** [comment]
I saw that nobody answered in the tabler repo, which unfortunately happens often there...

Why not simply changing it, if it causes issue?

**Comment by cavasinf** [comment]
Yeah, sadly non one answered 😞.
I've removed that part on the #3 PR.
