### ISSUE TITLE
Card always have padding bottom

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#49]
https://github.com/kevinpapst/TablerBundle/blob/3fc999c31d117b68bfed5860642f74d138193122/templates/embeds/card.html.twig#L16

With the current state, there's no way to remove padding bottom from embeded card.

```html
 <div ... class="card mb-3" ... >
```

How it looks today:
![image](https://user-images.githubusercontent.com/25293190/148238792-d2e64119-39dc-4655-baf7-d39c30f74ff0.png)

What I want to achieve:
![image](https://user-images.githubusercontent.com/25293190/148238857-506c354d-14d8-4620-9bf7-c7d55f8ce14b.png)

**Comment by kevinpapst** [comment]
Hm, simply removing `mb-3` is not an option. I have hundreds of card embeds that require the bottom margin. And the embed had a bottom margin since the first version of the AdminLTE bundle, so this BC break is not possible.

What is your proposal? Adding a new `bottom_spacer` variable which is true by default?

**Comment by cavasinf** [comment]
> I have hundreds of card

Also in my case.

Agree with the fact that the `mb-3` should be there by default.
The cases where it shouldn't be there are:
- when the card is the last from the page (:last-child).
- when there's only one card.


>What is your proposal? Adding a new bottom_spacer variable which is true by default?

IDK if we need a `variable` or a `block`.
`bottom_spacer` doesn't sound right for a variable, but good enough for a block name.

At the end, 
we need a `variable` which is called `margin_bottom` that is at true by default (private variable)

**Comment by kevinpapst** [comment]
From looking at your screenshot, it might be possible to use `.content div:last-of-type {margin-bottom: 0!important;}`. But only if the last div element is really a card. Seems there is no CSS way of selecting the last card if there are following elements on the page.
If that doesn't work: go ahead and add a variable.

**Comment by cavasinf** [comment]
Boostrap Spacing class shouldn't/cannot be overrided.
https://getbootstrap.com/docs/5.0/utilities/spacing/

That's why all style params have `!important`.

➡️ Need to add Variable for card embed

**Comment by kevinpapst** [comment]
`cannot` is not true AND I tested it before posting. Did you 😁 ?

<img width="1345" alt="Bildschirmfoto 2022-01-10 um 12 29 51" src="https://user-images.githubusercontent.com/533162/148759165-526c232b-5d79-49cb-ad14-128280c20637.png">

**Comment by kevinpapst** [comment]
> ➡️ Need to add Variable for card embed

Did some further testing: yes, we need a variable!
