### ISSUE TITLE
Login form - Tabulation navigation

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#5]
I can resolve that "issue" on my side by override some block,
but I want to know what is your (@kevinpapst) point of view about that.

In the Tabler demo : https://preview.tabler.io/sign-in.html
When you are in the input form, 
and try to move from `Email address` to `Password` by tabulation, 
it places you on `I forgot password`.

![LoginTabNavigation](https://user-images.githubusercontent.com/25293190/144813849-70434b5b-8ec8-4db4-97c2-e9f196f0a95d.gif)

It would be nicer if the tabulation action place us in the password input.

We can achieve that by adding `tabindex="-1"` in the HTML attr of the `<a>` tabler_password_reset link.

https://github.com/kevinpapst/TablerBundle/blob/5110ae631e47581880c668d456c20a9dd3d2bafa/templates/security.html.twig#L43

❓ The question is ❓ 
Do you allow in your bundle, extra functionalities/modifications that is not part from Tabler ?
Or do you try to keep as close as possible from the original ?

**Comment by kevinpapst** [comment]
The tab order should be optimized for the most common case: Email, password, remember me, login, social links and forgot password as last option.
I'd say we should fix that upstream, the risk is that this change could be potentially lost in an upstream sync (unlikely but possible).
If upstream won't change it, we can do it here.

**Comment by cavasinf** [comment]
Merged in https://github.com/kevinpapst/TablerBundle/pull/6
