### ISSUE TITLE
[Button] Bootstrap tooltip

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#58]
https://github.com/kevinpapst/TablerBundle/blob/8af12de25e69acc6658fed69eb331a2c532b6f47/templates/components/button.html.twig#L43

If using Tabler JS import file: 
- `data-toggle="tooltip"` supposed to be `data-bs-toggle="tooltip"`
https://github.com/tabler/tabler/blob/74985f8d008395d695d5ab1ad5b729684b00b8af/src/js/src/tooltip.js#L3

Should we use Tabler default behavior or Bootstrap configuration ?

**Comment by kevinpapst** [comment]
Oh, I am not using the JS file at all. 

Yeah, that is a tricky question because I tend to say: lets use the bootstrap default way. 

BUT the problem with that is: you cannot have an element that use the `data-bs-toggle` attribute twice like `<a href="#" data-bs-toggle="tooltip" data-bs-toggle="modal">` and that is why I did not change that attribute.

**Comment by cavasinf** [comment]
I tend to say: let's use the Tabler way. 😄

**Comment by kevinpapst** [comment]
We should probably write our own JS file that does work out of the box (eg. the different select for the tooltip) and that is compatible with SWUP. But that is a lot of additional maintenance. 

Different idea: we allow to configure the attribute in the macro and by default use `data-bs-toggle="tooltip"`.
I am using my own macro anyways and could always set this one attribute to `data-toggle="tooltip" ` for my own project.

**Comment by cavasinf** [comment]
> We should probably write our own JS file

> compatible with SWUP

I've already openned an issue to Tabler git, and I felt like the answer was a little "not my problem": https://github.com/tabler/tabler/issues/986

At the end, I've rewrite all the JS tabler file.
Using:
- dom
- export functions
- non self calling function

I can PR it, and remove those `-bs-` prefixes.

**Comment by cavasinf** [comment]
> you cannot have an element that use the data-bs-toggle attribute twice like `<a href="#" data-bs-toggle="tooltip" data-bs-toggle="modal">`



True true ...


It maybe the reason WHY tabler use `-bs-` for tooltip and default bootsrap beahvior for modal.
Same cases for:
- autosize
- dropdown
- popover
- tab
- toast

**Comment by kevinpapst** [comment]
> I've already openned an issue to Tabler git, and I felt like the answer was a little "not my problem": tabler/tabler#986

Yeah I saw that discussion and was a little disappointed as well about the answer.
Nowadays it should be common sense to write javascript in modules... 

Not sure if we should include your JS code here, because at the end I believe every bigger project will write its own javascript.

Honestly, when I started with the bundle here I needed a replacement that worked in my app, so I probably did some selfish decisions without thinking about it. It is very good that you use it with different settings, so we can identify these parts and fix them!

**Comment by cavasinf** [comment]
> Not sure if we should include your JS code here, because at the end I believe every bigger project will write its own javascript.

I'm fine with that

> It is very good that you use it with different settings, so we can identify these parts and fix them!

No problem 😉

**Comment by cavasinf** [comment]
Thinking about our DOC.

There's no information about that default JS file.
I've automatically added it to my project by "reflex" when I saw it.
But it should be good if we talk about it somewhere.

Like how to use/implement it AND the fact that we recommend to redo your own.

With Webpack:
```
.addEntry('tabler-bundle', './vendor/kevinpapst/tabler-bundle/assets/tabler.js')
```

```twig
{% block stylesheets %}
    ...
    {{ encore_entry_link_tags('tabler-bundle') }}
    ...
{% endblock %}

...

{% block javascripts %}
    ...
    {{ encore_entry_script_tags('tabler-bundle') }}
    ...
{% endblock %}
```

**Comment by kevinpapst** [comment]
More documentation is always a good idea!

But the file is actually used in the default layout, so for the very first step the users do not have to do anything:
https://github.com/kevinpapst/TablerBundle/blob/main/templates/layout.html.twig#L141

Or do I misunderstand you?

**Comment by cavasinf** [comment]
No it works, 
but I really don't like `<link>` and `<script>` raw HTML.

Symfony "good practices" 
tend to use Webpack to manage CSS and JavaScript : https://symfony.com/doc/current/frontend.html

**Comment by kevinpapst** [comment]
Why don't you like something that worked for 20 years now? 😁 

You can't handle it with Encore tags inside a bundle, so we have to do it that way.
If the user already uses Encore, that is probably one of the first things that he will adjust.
Maybe we should document it...

**Comment by cavasinf** [comment]
> Why don't you like something that worked for 20 years now? 😁

Look's like hard codded to me.
You don't have warnings or pre-checks available at building if something wrong.
Only showed when already in PROD with browser console. 😨 

Same case for CDN, hard codded, no version checking, a lot of problems for me 😵‍💫
