### ISSUE TITLE
Update Tabler assets

### ISSUE THREAD

**Issue by jerome2710** [kevinpapst/TablerBundle#63]
Could you update the CSS and JS with the latest version of Tabler? The package uses v1.0.0-beta2, while beta6 is currently the latest version. I am implementing some elements of the Tabler preview and have the feeling I'm missing some styling.

**Comment by kevinpapst** [comment]
Hi! Can you re-test latest master and let me know if it works now?

**Comment by jerome2710** [comment]
@kevinpapst Thank you for the quick fix, perfect! The styling is consistent now.

**Comment by kevinpapst** [comment]
Thanks for your feedback 👍
