### ISSUE TITLE
Auto-detection/Auto-completetion by IDE from vendor

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#7]
What IDE are you using ? 
Mine is PHPStorm and I don't know why but your Bundle with Tabler is not recognized by it.
AdminLTEBundle work like a charm, but not that one. 

TablerBundle:
![image](https://user-images.githubusercontent.com/25293190/144870914-17b320d4-d8a0-4c40-8749-8ea8d4e54776.png)

AdminLTEBundle:
![image](https://user-images.githubusercontent.com/25293190/144871224-83cd6710-4853-4d13-9c6a-b6ae145ce498.png)

It look's like he doesn't know where to find the `@Tabler`.
How do you declare the `@Tabler` isn't it from the `xxxxBundle.php`.

`TablerBundle.php` is deeper in the vendor directory than `AdminLTEBundle`.

![image](https://user-images.githubusercontent.com/25293190/144872749-9427bcc9-8062-4a92-ac04-9bb092a9d444.png)

**Comment by kevinpapst** [comment]
Works here, but PHPSTorm auto-detection sometimes fails. 

Check your preferences:
<img width="1733" alt="Bildschirmfoto 2021-12-06 um 16 19 39" src="https://user-images.githubusercontent.com/533162/144872454-b22a9678-754f-4db7-a9b2-8f2e73ed68af.png">

AdminLTEBundle was the old recommended directory structure for Symfony <= 4. 
Tabler already uses the new recommendated directory structure for Symfony >= 5.

**Comment by cavasinf** [comment]
Ok I've added two lines:
- First for your bundle references from vendor `vendor/kevinpapst/tabler-bundle/templates`
- Second for my template bundle override from my App `templates/bundles/TablerBundle`

![image](https://user-images.githubusercontent.com/25293190/144882576-43b4f8d0-19e1-448c-b31d-7def6b954ff0.png)

@kevinpapst Are your using this plugin for PhpStorm: https://github.com/Haehnchen/idea-php-symfony2-plugin
You can find it from the plugin's window from PhpStorm when typing Symfony.

The non discovery can be an issue from their side due to Symfony 5 🤔 
I don't have any project in that version.. So I can only speculate about that.

**Comment by kevinpapst** [comment]
I am using SF4 projects only right now. But it just works. I did not add these folders manually.

And yes, there is a reason why Haehnchen is in my "Sponsoring list":
<img width="484" alt="Bildschirmfoto 2021-12-06 um 17 28 34" src="https://user-images.githubusercontent.com/533162/144884094-93d4e6cd-7ee8-4a68-881d-f5bb193e7b27.png">


<img width="776" alt="Bildschirmfoto 2021-12-06 um 17 27 24" src="https://user-images.githubusercontent.com/533162/144883919-e260199e-b235-4dbb-b222-19408ed91aef.png">
