### ISSUE TITLE
[icon] extra class when FontAwesome

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#70]
Question: How to handle extra classes for `tabler_icon` macro ?
Keep in mind that tabler_icon should works with Tabler svg and FontAwesome.

Today:
```twig
{{ tabler_icon(icon, false, icon) }}
```

What it should be:
```twig
<i class="far fa-folder fa-7x"></i>
```

Any idea ?

**Comment by kevinpapst** [comment]
What about `<i class="{{ 'folder'|tabler_icon }} fa-7x"></i>` ?

That's how I use it.

**Comment by cavasinf** [comment]
Nice 👍
I knew you have a solution about that and I don't need to do a PR 😉
