### ISSUE TITLE
[csrf_token] Symfony 5 without FosUserBundle

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#8]
I'm currently migrating my project to Symfony 5.
FOSUserBundle being deprecated, I've unplugged it from my project.

But now I've an error at that line:

https://github.com/kevinpapst/TablerBundle/blob/5110ae631e47581880c668d456c20a9dd3d2bafa/templates/security.html.twig#L68-L70

![image](https://user-images.githubusercontent.com/25293190/145041642-c1267e49-6797-4886-b67c-a4553acc4c48.png)

### ❔ Who define that variable ❔ 

If I change the line by `{% if csrf_token | default(true) %}`, it works.
What is the purpose of that "if" condition ?

**Comment by kevinpapst** [comment]
Weird, that should check if the csrf_token() method is available.

I removed FOSUserBundle as well and have no problem with that line, but still running SF4 (not migrated to 5 yet).

**Comment by kevinpapst** [comment]
We can probably remove that code entirely. I just know that I had users that had the opposite problem. Without if the code failed when trying to run csrf_token method, which wasn't available in their context. But that was quite some time ago.
I cannot reproduce either case 🤷

**Comment by cavasinf** [comment]
> that should check if the csrf_token()

That what I thought.. 
I've tried to found the "best" way to check if a function/filter exist in twig and I don't really found something useful..


>We can probably remove that code entirely.

Instead of completely removing it, we can convert the `if` by a `block`.
That allow devs to override that block to remove the csrf if they want to 🤔

**Comment by kevinpapst** [comment]
Did you try `if csrf_token is defined` ?

If the defined check does not work, make it a block. I don't really care, because I truly hope that no one ever uses a login form with csrf token...

**Comment by cavasinf** [comment]
Yeah I've already tried it, and it returns `false`..

What is your twig version installed ?

```bash
root@bd73a300ef88:/var/www/html# composer show twig/twig
name     : twig/twig
descrip. : Twig, the flexible, fast, and secure template language for PHP
keywords : templating
versions : * v3.3.4

```

**Comment by kevinpapst** [comment]
```
name     : twig/twig
descrip. : Twig, the flexible, fast, and secure template language for PHP
keywords : templating
versions : * v3.3.3
```

But the csrf_token() method is coming from the framework or security bundle, not sure without looking it up.

**Comment by cavasinf** [comment]
I wasn't looking for the `csrf_token()` method, but the way twig interpret the `if` condition but you are n V3 too.

Anyway, like you, 
I don't get why people doesn't want to use the csrf, but I can switch it into block.

**Comment by kevinpapst** [comment]
Which seems to be some old code that is not required. I have to delete it. As you have to change the template anyways: choose the solution you want. Removing the if is a stronger statement for best security practices. Having a block makes it more configurable. I would merge both...
