### ISSUE TITLE
Alert macro and `alert-important` class

### ISSUE THREAD

**Issue by cavasinf** [kevinpapst/TablerBundle#89]
Why the class `alert-important` is automated when `title` or `description` are empty?

https://github.com/kevinpapst/TablerBundle/blob/0adfe1668516918f8fddb05f848bb28707e4a99e/templates/components/alert.html.twig#L3

It blocks me to add title + description AND full alert background color.
I don't think it is a good idea.

We can let this automation but add a new param `important` and change de background condition like
`{% set background = title is empty or description is empty or important ? true : false %}`

**Comment by kevinpapst** [comment]
Your suggestion looks good to me 👍 

Probably clarify with `or important is same as (true)` otherwise it might fail if you pass `false`

Question: there are already too many params, shall we add an options array? We could do something like:
```twig
{% macro alert(type, description, title, icon, dismissible) %}
  {% if type is iterable %}
    {% set options = type %}
    {% set type = options.type %}
    {% set important = options.important %}
    ...
```
Then it would be possible to pass all values as one param array.

Or we build some helper macros that allow to call it with less params:

```twig
{% macro alert_important(description, title, icon) %}
  {{ self.alert('danger', description, title, icon, false, true) %}
```

**Comment by cavasinf** [comment]
Due to:
- `alert-title` when title is set.
- `text-muted` when description is set.

There is no work around to manually add that class.
```twig
{{ alert('danger  alert-important', 'Vous allez clôturer le désordre : trigger ?' ,'Cloture du désordre', 'fas fa-exclamation-triangle') }}
```
Current:
![image](https://user-images.githubusercontent.com/25293190/171131218-eb6fc110-db91-46ba-b80b-cd30cb5c65d3.png)

Should be:
![image](https://user-images.githubusercontent.com/25293190/171131339-41e2682c-a0ea-4611-87fa-1f7af9225b57.png)

**Comment by cavasinf** [comment]
> Question: there are already too many params, shall we add an options array?

Yeah, I've though the same thing..
Do you want to handle this macro params to not have BC break ?

As other components, they have only one `options` param.
And this allow us to add/modify code or params without breaking other dev macro usage.
But convert all current params to one param will BC break..

**Comment by kevinpapst** [comment]
Yes, even though still in pre-release state, I would avoid BC breaks. 

Can you start with that? Untested and (be careful) typed here in Github 😁 

```twig
{% macro alert(type, description, title, icon, dismissible) %}
  {% if type is iterable %}
    {% set options = type %}
    {% set title = options.title is defined ? options.title : null %}
    {% set description = options.description is defined ? options.description : null %}
    {% set type = options.type is defined ? options.type : 'danger' %}
    {% set important = options.important is defined ? options.important : false %}
    {% set dismissible = options.dismissible is defined and options.dismissible is same as (true) ? true : false %}
    {% set background = title is empty or description is empty ? true : false %}
  {% else %}
    {% deprecated 'Passing multiple parameter to "alert" macro  is deprecated, use options array syntax.' %}
    {% set dismissible = dismissible is same as (true) ? true : false %}
    {% set background = title is empty or description is empty ? true : false %}
```

**Comment by cavasinf** [comment]
OK I'll try that.

---------------------

Other thing that "tickles" me:
- Auto `|trans` on every text variables. 

https://github.com/kevinpapst/TablerBundle/blob/0adfe1668516918f8fddb05f848bb28707e4a99e/templates/components/alert.html.twig#L12-L22

I don't really like the fact that we are translating texts that is not part of our domain TablerBundle (`trans({}, 'TablerBundle')`).

The cons of that is when devs use symfony function `php bin/console translation:extract --force fr`, 
to auto detect translations, they will not be detected.

#### Examples 
- `{{ alert('danger', 'label.danger') }}` is **NOT** auto detected.
- `{{ alert('danger', 'label.danger'|trans) }}` is auto detected.

So why using `{{ description|trans }}` if dev already passing a translated string?

**Comment by kevinpapst** [comment]
Good point! I think you can keep the trans filter in the "deprecated else branch" and remove the translation from the new options.

```twig
{% else %}
    {% deprecated 'Passing multiple parameter to "alert" macro  is deprecated, use options array syntax.' %}
    {% set title = title is not empty ? title|trans : title %}
    {% set description = description is not empty ? description |trans : description %}
```
