### ISSUE TITLE
Update Tabler to 1.0.0-beta10

### ISSUE THREAD

**Issue by wucherpfennig** [kevinpapst/TablerBundle#95]
See: https://github.com/tabler/tabler/releases/tag/v1.0.0-beta10

**Comment by kevinpapst** [comment]
Tried but failed: https://github.com/tabler/tabler/issues/1147

**Comment by wucherpfennig** [comment]
Well basically just for the new `datagrid` component 😉

but I have figured that it is basically just a shortcut to some bs5 classes.

Therefore it is not the most important thing to me.

> You use the package and don't have node and yarn installed? That's fascinating 😁 It is extremely simple to setup, but I can have a look as well.
> 
> I am carful with merges of Tabler, because unfortunately the maintainer is pretty careless with merges ... introduces bugs and then disappears for weeks. And the current version is pretty stable for me.
> 
> Any real reason why you want that update? I'll give it a try anyway, just curious...

Well I have all those tools available in my environment but as I am lacking the knowledge how to do this update "quickly with minimal efforts" while being able to create a merge request I gave up 😁

Actually I was just interested in the new `datagrid` component but I figured this component is just a wrapper for some bs5 classes... therefore it is not the most important thing to me 😎

**Comment by kevinpapst** [comment]
A simple `yarn upgrade` followed by `yarn run prod` would do the trick.

I am using the data grid component already, just had to add the following SASS to my project:
```
$datagrid-padding: 1.5rem !default;
$datagrid-item-width: 15rem !default;

.datagrid {
    --#{$variable-prefix}datagrid-padding: #{$datagrid-padding};
    --#{$variable-prefix}datagrid-item-width: #{$datagrid-item-width};

    display: grid;
    grid-gap: var(--#{$variable-prefix}datagrid-padding);
    grid-template-columns: repeat(auto-fit, minmax(var(--#{$variable-prefix}datagrid-item-width), 1fr));
}

.datagrid-title {
    @include subheader;
    margin-bottom: .25rem;
}
```
Titles are not perfect but this will be fixed with the next tabler update. And then the code can be removed again.

**Comment by wucherpfennig** [comment]
Just out of curiosity: Why are you building the tabler theme yourself if you do not modify the sass?

E.g. In #81 I proposed some minor changes to the (tabler) source which we could easily implement while tabler is not advancing in our favours (fontawesome). In those cases I would understand (although not favourable / desirable) to build and include custom fixes and build ourselves.

But in the meantime (without modifying the tabler sass) we could just provide the minified css as the result is the same?

BR wucherpfennig

**Comment by wucherpfennig** [comment]
> To make it compatible with Webpack Encore and the Symfony world. Without that, we would have to copy the assets from the node modules folder manually and then hardcode the directory in the ` {{ assets() }}` calls.

I thought so after I have added my comments yesterday 😄

I will close again this issue as I think we should focus on providing more functionality rather than focusing one some technicalities.

**Comment by kevinpapst** [comment]
Having additional CSS rules, e.g. for font awesome is totally fine, I am just not having troubles with the icons, so please provide a PR. which is easily testable.

**Comment by kevinpapst** [comment]
Still no data grid in beta10 as I see ... nevertheless we can close here?!
