### ISSUE TITLE
Component - Accordion

### ISSUE THREAD

**Issue by wucherpfennig** [kevinpapst/TablerBundle#99]
I do need the accordion quite often. Therefore I decided to write a macro to implement in the project.

(FYI https://github.com/kevinpapst/TablerBundle/pull/82#issuecomment-1135955816)

Before I add a PR (with docs etc.) please comment on the macro. 

* I do need the `extraClass` on the item level to indicate some success / danger etc.  
  I would very much keep this extra functionality 😉
* I noticed that `extraClass` on `title` and / or `body` cause the affected element to animate poorly.
  I do think we do not need that...
* Accordions have no `mb-3` as default
  Should we add it if `extraClass` is not set?
* Accordions have no `background` as default
  Should we add it if `extraClass` is not set?

```twig
{% macro accordion(items, options) %}
    {% set _id = options.id ?? ('accordion-' ~ random(0, 999)) %}
    {% set _raw = options.raw ?? true %}
    {% set _flush = options.flush ?? false %}
    {% set _always_open = options.always_open ?? false %}
    {% set _extraClass = options.extraClass ?? '' %}

    <div id="{{ _id }}" class="accordion {% if _flush == true %}accordion-flush{% endif %} {{ _extraClass }}">
        {% for item in items %}
            {% set _id_collapse = _id ~ '-collapse-' ~ loop.index %}
            {% set _item_extraClass = item.options.extraClass ?? '' %}
            {% set _item_title_extraClass = item.options.title_extraClass ?? '' %}
            {% set _item_body_extraClass = item.options.body_extraClass ?? '' %}
            <div class="accordion-item {{ _item_extraClass }}">
                <div class="accordion-header {{ _item_title_extraClass }}" id="{{ _id }}-heading-{{ loop.index }}">
                    <button class="accordion-button {% if loop.first == false %}collapsed{% endif %}"
                            type="button" data-bs-toggle="collapse" data-bs-target="#{{ _id_collapse }}"
                            aria-expanded="true">
                        {% if _raw == true %}{{ item.title | raw }}{% else %}{{ item.title }}{% endif %}
                    </button>
                </div>
                <div id="{{ _id_collapse }}" {% if _always_open == false %}data-bs-parent="#{{ _id }}"{% endif %}
                     class="accordion-collapse collapse {% if loop.first %}show{% endif %} {{ _item_body_extraClass }}">
                    <div class="accordion-body pt-0">
                        {% if _raw == true %}{{ item.body | raw }}{% else %}{{ item.body }}{% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endmacro %}
```

Usage:

```twig
     {% embed '@Tabler/embeds/card.html.twig' %}
        {% block box_body %}
            {% from 'macro/accordion.html.twig' import accordion %}

            {% set items =
                {
                    'key1':
                    {
                        'title': 'Title 1',
                        'body': 'Body 1',
                    },
                    'key2':
                    {
                        'title': 'Title 1',
                        'body': 'Body 2',
                        'options':
                        {
                            'title_extraClass': 'bg-success text-white',
                            'body_extraClass': 'bg-danger pt-3',
                        },
                    },
                    'key3':
                    {
                        'title': 'Title 3',
                        'body': 'Body 3',
                        'options':
                        {
                            'extraClass': 'bg-danger-lt'
                        }
                    },
                    'key4':
                    {
                        'title': '<div>Title 4 <strong>with HTML</strong></div>',
                        'body': '<div>Body 4 <strong>with HTML</strong></div',
                    },
                } %}

            {% set options = {
                'id': 'example-accordion',
                'raw': null,
                'always_open': false,
                'extraClass': 'mb-0',
            } %}

            {{ accordion(items, options) }}

        {% endblock %}
    {% endembed %}
```

![grafik](https://user-images.githubusercontent.com/3634653/177017271-68d86eac-c12b-48ed-8314-412a81a26476.png)

**Comment by wucherpfennig** [comment]
In addition to the questions above:

@kevinpapst What do you think about using `DTO` for UI elements?

Personally I do use https://github.com/spatie/data-transfer-object quite extensively for all sorts of matter.

A `accordionItem` DTO would ease the use of this macro alot... but would also add a lot of overhead. 

One big thing I like about DTO is the usage like:

```twig
{# @var item \App\Entity\ProductLifecycleManagement\ProductLifecycleManagementTableDTO #}
```

which provides you with autocompletion in Twig (at least in PHPSTORM).

**Comment by kevinpapst** [comment]
Again, theoretical feedback is complicated... I didn't use this component or now.

> I do need the extraClass on the item level to indicate some success / danger etc. I would very much keep this extra functionality 😉

We built this bundle for us and if other people find it use-full: hooray 🎉 

> I noticed that extraClass on title and / or body cause the affected element to animate poorly. I do think we do not need that...

Sounds as if you are right. 

> Accordions have no mb-3 as default. Should we add it if extraClass is not set?

If it looks crappy without: yes.

> Accordions have no background as default. Should we add it if extraClass is not set?

I don't get that. What kind of background would you apply automatically? 

>  What do you think about using DTO for UI elements?

I like the idea, but it makes everything more complicated. And it somehow defeats the split between back- and frontend. The backend dev would have to create the DTO and fill it with the correct data, expected by the frontend component. Personally I try to pass the raw data to twig and them manipulate it so it works with the component.

Anyway: I would avoid adding any kind of dependency to the bundle.

**Comment by wucherpfennig** [comment]
**About the defaults (can also be applied to #100):**
After thinking about it I would argue against my first proposal.

I do not think that the theme was built to use components outside of some sort of "content boxes". If so you are responsible yourself to add styles etc. Hence I assume that most of the cases you had to overwrite "defaults" which is kind of the opposite of why they were placed there in the first place...

**Regarding the DTO**
I am using `DTO` heavily and it helps me to abstract the database entities from the frontend. I am finding it simpler an easier to create / modify objects in a service and pass that modified object to a controller in order to render it.

I tested my approach + creating additional matching `DTO` for using macros from this theme and I realized that I was forced to do stuff twice. Once to obtain the `DTO` from my Service and a second time to fit this first `DTO` into the theme's.

I think this (my) approach how I do stuff "usually" is the tradeoff which I have to pay as I do not have to create custom tailored components which were specifically built to accept (one or more) types of my custom `DTO`.

**Comment by kevinpapst** [comment]
I usually pass the Doctrine entities/collections/whatever to Twig but then I have a small abstraction layer between my app and the theme. It helps me to apply app specific settings everywhere and it helps to bring the data into the correct structure.

I have a file with many macros inside, which every template loads and these macros take my app specific structure and convert them into calls to the theme macro. A very very simple example, just for clarification:
```
{% macro alert(type, description, title, icon, dismissible) %}
    {% from '@theme/components/alert.html.twig' import alert %}
    {{ alert({type: type, description: description|trans, title: title|trans, icon: icon, dismissible: dismissible}) }}
{% endmacro %}
```

Instead of the 5 parameter you could pass in an AlertDTO as well.
These macros allowed me to switch from AdminLTE to Bundler rather quickly, because I only had to adapt all the macros and not touch every template manually.
